version: "3.8"
services:
  eureka-service:
    container_name: eureka-service
    image: josemiguelchvz/eureka-service:latest
    ports:
      - "8761:8761"
  gateway-service:
    container_name: gateway-service
    image: josemiguelchvz/gateway-service:latest
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka/
    ports:
      - "8080:8080"
    depends_on:
      - eureka-service
    links:
      - eureka-service
  mysql:
    image: mysql
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: employee
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
  employee-service:
    container_name: employee-service
    image: josemiguelchvz/employee-service:latest
    ports:
      - "30001:8081"
    environment:
        - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka/
        - DB_URL=jdbc:mysql://mysql:3306/employee?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
        - DB_USERNAME=root
        - DB_PASSWORD=password
    deploy:
        restart_policy:
          condition: on-failure
    depends_on:
      - eureka-service
      - mysql
    links:
      - eureka-service
  postgres:
    image: postgres:13.2
    container_name: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=schedule
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: always
  schedule-service:
    container_name: schedule-service
    image: josemiguelchvz/schedule-service:latest
    ports:
      - "30002:8082"
    environment:
        - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka/
        - DB_URL=jdbc:postgresql://postgres:5432/schedule
        - DB_USERNAME=postgres
        - DB_PASSWORD=password
    deploy:
        restart_policy:
          condition: on-failure
    depends_on:
      - eureka-service
      - postgres
    links:
      - eureka-service
  report-service:
    container_name: report-service
    image: josemiguelchvz/report-service:latest
    ports:
      - "30003:8083"
    environment:
        - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka/
    deploy:
        restart_policy:
          condition: on-failure
    depends_on:
      - eureka-service
    links:
      - eureka-service
  frontend-service:
    container_name: frontend-service
    image: josemiguelchvz/frontend-service:latest
    ports:
      - "3000:3000"
volumes:
  db_data: