spring:
  application:
    name: employee-service
  cloud:
    kubernetes:
      enabled: false
  jpa:
    show-sql: false
    hibernate:
      dialect: MySQL8Dialect
      ddl-auto: create
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
server:
  port: 8081
  forward-headers-strategy: framework
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}