spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee**
        - id: schedule-service
          uri: lb://schedule-service
          predicates:
            - Path=/schedule**
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/report**
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}