spring:
  application:
    name: report-service
  cloud:
    kubernetes:
      enabled: false
server:
  port: 8083
  forward-headers-strategy: framework
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}