apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: employee-service
  name: employee-service
spec:
  selector:
    app: employee-service
  ports:
    - name: 8081-8081
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
status:
  loadBalancer: {}