apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - name: 8080-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
status:
  loadBalancer: {}