apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service
spec:
  selector:
    matchLabels:
      app: eureka-service
  replicas: 3
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
        - name: eureka-service
          image: josemiguelchvz/eureka-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: eureka-service-svc
spec:
  selector:
    app: eureka-service
  ports:
    - protocol: "TCP"
      port: 8761 # The port that the service is running on in the cluster
      targetPort: 8761 # The port exposed by the service
  type: NodePort # type of the service.